const waivers = {
  info: [
    {
      id: 0,
      waiver: 'John Doe, Group Name, Name of the waiver.pdf',
      name: 'John Doe',
      role: 'Participant',
      // maybe change to Date() object?
      date: 'MM/DD/YYYY',
      notes: 'no glue gun',
      status: 'Approved',
    },
    {
      id: 1,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'glue gun',
      status: 'Approved',
    },
    {
      id: 2,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'none',
      status: 'Approved',
    },
    {
      id: 3,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'glue gun',
      status: 'Approved',
    },
    {
      id: 4,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'none',
      status: 'Approved',
    },
    {
      id: 5,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'glue gun',
      status: 'Approved',
    },
    {
      id: 6,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'none',
      status: 'Approved',
    },
    {
      id: 7,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'none',
      status: 'Approved',
    },
    {
      id: 8,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'glue gun',
      status: 'Approved',
    },
    {
      id: 9,
      waiver: 'John Doe, Name of the waiver',
      name: 'Name',
      role: 'Participant',
      date: 'MM/DD/YYYY',
      notes: 'none',
      status: 'Approved',
    },
  ],
};
export default waivers;
